# Generated by Django 5.1.4 on 2025-01-03 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_original_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='sale_price',
        ),
    ]
